# Generated by Django 5.2.13 on 2026-06-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISIONTECH', '0003_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Optional URL or static path to brand logo/image', max_length=500),
        ),
    ]
